/*
Deployment script for 961DA04DF2C533828D76052EE8DFB1DC_N-DEVELOPMENT-WITH-.NET-CORE-3.0\CHAPTER5\DRAKEN.CRM\DRAKEN.REPOSITORY\DATA\DRAKEN.CRM.DATA.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "961DA04DF2C533828D76052EE8DFB1DC_N-DEVELOPMENT-WITH-.NET-CORE-3.0\CHAPTER5\DRAKEN.CRM\DRAKEN.REPOSITORY\DATA\DRAKEN.CRM.DATA.MDF"
:setvar DefaultFilePrefix "961DA04DF2C533828D76052EE8DFB1DC_N-DEVELOPMENT-WITH-.NET-CORE-3.0\CHAPTER5\DRAKEN.CRM\DRAKEN.REPOSITORY\DATA\DRAKEN.CRM.DATA.MDF_"
:setvar DefaultDataPath "C:\Users\karthick-win\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\karthick-win\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Table]...';


GO
CREATE TABLE [dbo].[Table] (
    [Id]            INT            NOT NULL,
    [FirstName]     NVARCHAR (50)  NULL,
    [LastName]      NVARCHAR (50)  NULL,
    [Designation]   NVARCHAR (50)  NULL,
    [Email]         NVARCHAR (50)  NULL,
    [BusinessPhone] NVARCHAR (15)  NULL,
    [MobilePhone]   NVARCHAR (15)  NULL,
    [status]        INT            NULL,
    [LinkedIn]      NVARCHAR (50)  NULL,
    [Street1]       NVARCHAR (250) NULL,
    [Street2]       NVARCHAR (250) NULL,
    [City]          NVARCHAR (100) NULL,
    [State]         NVARCHAR (100) NULL,
    [Country]       NVARCHAR (100) NULL,
    [ZipCode]       NVARCHAR (15)  NULL,
    [CreatedDate]   DATETIME       NULL,
    [ModifiedDate]  DATETIME       NULL,
    [CreatedBy]     NVARCHAR (50)  NULL,
    [ModifiedBy]    NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
